eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka


spring:
  profiles:
    active: dev

  mail:
    endereco-remetente: luanalencar134@gmail.com
    nome-remetente: Luan Alencar

  application:
    name: Acesso Service

server:
  port: 8087

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    date-format: dd-MM-yyyy
    deserialization:
      fail-on-unknown-properties: false
  datasource:
    url: jdbc:postgresql://localhost:5429/acessoservice
    username: acessoservice
    password: acessoservice
  liquibase:
    change-log: classpath:/config/liquibase/master.xml

      cloud:
        stream:
        bindings:
        mailer:
        destination: mailer

  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: sgegestaoeventos@gmail.com
    password: sgesge123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          quitwait: false

application:
  feign:
    url-documents: http://localhost:8081
