spring:
  application:
    name: Gateway API
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: configserver, usuarioservice, eurekaserver, documentservice
          uri: lb://configserver, lb://usuarioservice, lb://eurekaserver, lb://documentservice
          predicates:
            - Path=/configserver/**
            - Path=/usuarioservice/**
            - Path=/eurekaserver/**
            - Path=/documentservice/**

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8083/eureka

server:
  port: 1111