spring:
  application:
    name: Gateway API
  main:
    web-application-type: reactive

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      default-zone: http://localhost:8761/eureka

server:
  port: 1111