version: '2'
services:
  minio:
    image: minio/minio
    ports:
      - 9000:9000
    environment:
      - 'MINIO_ACCESS_KEY=acessoservice'
      - 'MINIO_SECRET_KEY=acessoservice'
    command: server /data