eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka

spring:
  profiles:
    active: dev

  application:
    name: Acesso Service

server:
  port: 8087

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    date-format: dd-MM-yyyy
    deserialization:
      fail-on-unknown-properties: false
  datasource:
    url: jdbc:postgresql://localhost:5429/acessoservice
    username: acessoservice
    password: acessoservice
  liquibase:
    change-log: classpath:/config/liquibase/master.xml
application:
  feign:
    url-documents: http://localhost:8081
